### ISSUE TITLE
ClassName is missing ??

### ISSUE THREAD

**Issue by tsrCodes** [Quartz/wp-graphql-content-blocks#15]
Here's the query

```gql
query post {
  post(id: "1", idType: ID) {
    content(format: RENDERED)
    blocks {
      tagName
      innerHtml
    }
  }
}
```

The Output of Content String 

```html
<pre><code class=\"language-python\">\n\nfrom math import *\nprint(&quot;The Value of PI is &quot;, pi)</code></pre>
```

### With Blocks

```
        {
          "tagName": "pre",
          "innerHtml": "<code>from math import *print(\"The Value of PI is \", pi)</code>"
        },
```

className is missing with blocks !! Any Idea ??

**Comment by chriszarate** [comment]
This is intentional, since it's assumed that most inline attributes are not useful (especially those that convey styling that will likely not be available where this data is consumed). Details:

https://github.com/Quartz/wp-graphql-content-blocks#block-definitions

Of course, if your use case differs, you can update or filter the block definitions:

https://github.com/Quartz/wp-graphql-content-blocks/blob/master/src/types/shared/block-definitions.php#L191
https://github.com/Quartz/wp-graphql-content-blocks/blob/master/src/types/shared/block-definitions.php#L316

**Comment by tsrCodes** [comment]
Got It !! Thanks for Quick Reply : )
